Reduce or op cpufallback (#5814)
### Ticket
#3883 

### Problem description
Theoretical support for hoisting TTIR ReduceOrOp to CPU fallback has
been added; however, while the op compiles, it fails at runtime with an
error like:
```
FAILED test/python/golden/test_ttir_ops.py::test_hoisted_reduce_or[ttnn-dim_args0-4x4] - builder.base.builder_utils.TTBuilderGoldenException: Failed: program-level output golden comparison failed, actual_pcc=0.2947140183650278 < expected_pcc=0.99
FAILED test/python/golden/test_ttir_ops.py::test_hoisted_reduce_or[ttmetal-dim_args0-4x4] - builder.base.builder_utils.TTBuilderGoldenException: Failed: program-level output golden comparison failed, actual_pcc=0.29421406235980374 < expected_pcc=0.99
```
### What's changed
The TTIRToTTIRDecomposition pattern of ReduceOR op was simply mapping it
to a simple reduce sum. More have been added to mimic the ReduceOr (sum,
compare, notEqual, typecast) Ops to be more aligned with the semantic of
Reduce_or.
casted the reduce_or_golden output to float for type conformity (though
we might need to later adapt in case of a tensor with integer values)

### Checklist
- [ ] New/Existing tests provide coverage for changes

---------

Co-authored-by: Vincent Wells <vwells@tenstorrent.com>