Revert "Remove all_reduce decomposition workaround (#8313)" (#8382)
This reverts commit a4dc183d9300046136828e75d7dda188f476964d.

### Problem description
This commit caused failures on tt-mlir uplift into tt-xla:
1.
https://github.com/tenstorrent/tt-xla/actions/runs/25619651241/job/75346483152
(One of very few tests that actually checks for coherence model
outputs.)
```
tests/integrations/vllm_plugin/sampling/test_sampling_params.py::test_output_coherence[n300_llmbox]
AssertionError: Expected '2' in output for '1 + 1 =', got: '  ever,  ever,  ever, '
```
2.
https://github.com/tenstorrent/tt-xla/actions/runs/25619651241/job/75346483294
```
tests/torch/models/llama3/test_llama_step_n300.py::test_llama_step
Always | TT_THROW: TIMEOUT: device timeout in fetch queue wait, potential hang detected (assert.hpp:104)
```
3.
https://github.com/tenstorrent/tt-xla/actions/runs/25619651241/job/75346483265
```
examples/pytorch/multichip/n300/test_mnist_tp_inference.py::test_mnist_inference_tensor_parallel[128-784]
Always | TT_THROW: ShapeBase[] index out of range. 1 not in [-4, 1) (assert.hpp:104)
```