fix build warning -Wreturn-type
We are hitting build failure in `tt-forge-fe` for latest `tt-mlir`
(build warning treated as error):

error: non-void function does not return a value in all control paths

Refactored function so that it always returns.