[EmitC] Fix function name collision (#3245)
### Ticket
https://github.com/tenstorrent/tt-mlir/issues/3240

### Problem description
`TTNNCreateInputGenerators` creates `main` and
`createInputsFor_${funcName}`. If one of the existing module functions
have the same name, it will cause a name collision and module's symbol
table will report a following error during verification
```
error: redefinition of symbol named '${funcName}'
```

### What's changed
- prepended a `_` to all existing functions to avoid name collision
(namespaces would be a better idea in C++, but that would require major
refactoring of the pass pipeline; if someone has a better idea, please
let me know)
- decided to refactor the whole `TTNNCreateInputGenerators`, which I'm
sure will make extending the generation of inputs to different creation
functions a much easier task in the future

### Checklist
- [x] New/Existing tests provide coverage for changes